services:
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    user: "${LOCAL_UID}:${LOCAL_GID}"

    working_dir: /workspace

    env_file:
      - ../.env

    environment:
      TZ: America/Los_Angeles
      D4J_HOME: /opt/defects4j
      HOME: /tmp

    volumes:
      - ..:/workspace
      - ${D4J_ROOT}:/opt/defects4j

    stdin_open: true
    tty: true